import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Lottie from 'lottie-react'

import logoAnimation from '../animations/animated-logo.json'

export default function Home() {

  const style = {
    height: 300,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Lottie 
            animationData={logoAnimation}
            style={style}
          />
      </main>
    </>
  )
}
