import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Lottie from 'lottie-react'

import logoAnimation from '../animations/animated-logo.json'

export default function Home() {
  const [isLoaded, setIsLoaded] = useState(true);
  const [roleIndex, setRoleIndex] = useState("");

  const roles = ["Graphic Design", "Motion Graphic Designer", "UI/UX Design", "Product Designer"]

  useEffect(() => {
    setTimeout(() => {
      setIsLoaded(false);
      console.log('loaded');
    }, 9000);
  }, []);

// useeffect function that changes roles every 3 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      setRoleIndex((roleIndex + 1) % roles.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [roleIndex]);


  const style = {
    height: 300,
  };

  return (
    <>
      <Head>
        <title>Hi, I'm Ivan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isLoaded === true ? 
          <div className={styles.animationCont}>
            <Lottie 
              animationData={logoAnimation}
              style={style}
              loop={false}
            />
          </div>
        : <></>}
        <div>
          <h1>Hi, I'm Ivan Li</h1>
          <div>
            I am a {roles[roleIndex]}
          </div>
        </div>
      </main>
    </>
  )
}
