import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Lottie from 'lottie-react'

import paper from '../public/paper.jpg'

import logoAnimation from '../animations/Lottie.json'

export default function Home() {
  const [isLoaded, setIsLoaded] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoaded(false);
      console.log('loaded');
    }, 9000);
  }, []);

  const style = {
    height: 300,
  };

  return (
    <>
      <Head>
        <title>Hi, I'm Ivan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.vignette}>
        <Image className={styles.texture} src={paper}/>
        </div>
        {isLoaded === true ? 
          <div className={styles.animationCont}>
            <Lottie 
              animationData={logoAnimation}
              style={style}
              loop={false}
            />
          </div>
        : <></>}
        {isLoaded === false ?
          <div className={styles.mainCont}>
            <div className={styles.nameCont} id='name'>
              <h1>Hi, I'm Ivan.</h1>
            </div>
            <div className={styles.photoCont} id='photo'>
              <img 
                src="ivan-li.png" 
                alt="Ivan Li" 
              />
              <div className={styles.rolesCont}>
                <h2 id='role1'>Digital Designer</h2>
                <h2 id='role2'>Graphic Designer</h2>
                <h2 id='role3'>Motion Graphic Designer</h2>
                <h2 id='role4'>UI/UX Designer</h2>
              </div>
            </div>
            <button className={styles.button} id='button'>
              <a href='http://portfolio.ivanghl.com/projects/' target="_blank">View Portfolio</a>
            </button>
          </div>    
        : <></>}
      </main>
    </>
  )
}
